name: BSE Problem Set 1
run-name: Test workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      basis:
        description: "Basis Set"
        required: true
      format:
        description: "File Format"
        required: true
      elements:
        description: "Elements"
        required: true

jobs:
  matrix_jobs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        basis: [sto-3g, 6-31g]
        format: [json, nwchem]
        elements: [H-Ne, C, N, O]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t bse:dev .

      - name: Run Docker container & download files
        run: |
          docker run --rm -v "$(pwd):/output" bse:dev \
            ${{ matrix.basis }} \
            ${{ matrix.format }} \
            ${{ matrix.elements }}

      - name: Display Downloaded Files
        run: |
          ls -l
          cat *.${{ matrix.format }} 

  manual_dispatch_job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t bse:dev .

      - name: Run Docker container with manual inputs
        run: |
          docker run --rm -v "$(pwd):/output" bse:dev \
            "${{ github.event.inputs.basis }}" \
            "${{ github.event.inputs.format }}" \
            "${{ github.event.inputs.elements }}"

      - name: Show Downloaded File
        run: |
          ls -l
          cat *.${{ github.event.inputs.format }} 
