name: BSE Problem Set 1
run-name: Test workflow
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:
    inputs:
      basis:
        description: "Basis Set"
        required: true
      format:
        description: "File Format"
        required: true
      elements:
        description: "Elements"
        required: true

jobs:
  matrix_jobs:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        basis: [sto-3g, 6-31g]
        format: [json, nwchem]
        elements: [H-Ne, C,8,p-17]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t bse:dev .

      - name: Run Docker container to download BSE files
        run: |
          docker run --rm -v "$(pwd):/output" bse:dev \
            ${{ matrix.basis }} \
            ${{ matrix.format }} \
            ${{ matrix.elements }}

      - name: Display downloaded files from host
        run: |
          ls -l output/
          cat output/*.${{ matrix.format }}

  manual_dispatch_job:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bse:dev .

      - name: Run Docker container with manual inputs
        run: |
          docker run --rm -v "$(pwd):/output" bse:dev \
            "${{ github.event.inputs.basis }}" \
            "${{ github.event.inputs.format }}" \
            "${{ github.event.inputs.elements }}"

      - name: Display downloaded files from host (manual input)
        run: |
          ls -l output/
          cat output/*.${{ github.event.inputs.format }}
