name: BSE Problem Set 1
run-name: Test workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      basis:
        description: "Basis Set"
        required: true
      format:
        description: "File Format"
        required: true
      elements:
        description: "Elements"
        required: true

jobs:
  matrix_jobs:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        basis: [sto-3g, 6-31g]
        format: [json, nwchem]
        elements: [H-Ne, C, N, Invalid]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bse:dev .

      - name: Run Docker container to download BSE files
        shell: bash
        run: |
          mkdir -p output
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            docker run --rm -v "${{ github.workspace }}/output:/output" bse:dev \
              ${{ matrix.basis }} \
              ${{ matrix.format }} \
              ${{ matrix.elements }}
          else
            docker run --rm -v "$(pwd)/output:/output" bse:dev \
              ${{ matrix.basis }} \
              ${{ matrix.format }} \
              ${{ matrix.elements }}
          fi

      - name: Display downloaded files from host
        run: |
          ls -l output/ || echo "No files found"
          cat output/*.${{ matrix.format }} || echo "No valid files to display"

  ubuntu_docker_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Docker on Ubuntu
        run: |
          docker pull ubuntu:22.04
          docker run --rm ubuntu:22.04 echo "hello from container"

  windows_docker_job:
    runs-on: windows-latest
    steps:
      - name: Use Docker on Windows
        run: |
          docker pull mcr.microsoft.com/windows/servercore:ltsc2022
          docker run --rm mcr.microsoft.com/windows/servercore:ltsc2022 powershell -Command "Write-Output 'hello from a windows container'"

  macos_docker_job:
    runs-on: macos-latest
    steps:
      - name: Install Docker on macOS
        run: |
          brew install docker docker-compose
          colima start || true

      - name: Start Docker Daemon
        run: |
          sudo dockerd > /dev/null 2>&1 &
          sleep 5

      - name: Use Docker on macOS
        run: |
          docker pull ubuntu:22.04
          docker run --rm ubuntu:22.04 echo "hello from container"


